- name: install php-fpm and etc
  apt: name={{ item }} state=installed
  with_items:
       - php
       - php-mysql
      # - php-mbstring
       - php-fpm

- name: copy php-fpm config
  template: src=php.ini dest=/etc/php/7.0/fpm/ 

- name: restart & enable php-fpm
  service: name=php7.0-fpm state=restarted enabled=yes      
